apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: wind-turbine
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    version: 3.8.0
    config:
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: secure
        port: 9094
        tls: true
        type: route
        authentication:
          type: scram-sha-512
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: my-cluster
    app.kubernetes.io/component: kafka
    app: wind-turbine
    app.kubernetes.io/part-of: wind-turbine
spec:
  replicas: 3
  roles:
  - controller
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 2Gi
      kraftMetadata: shared
      deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: my-cluster
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: wind-turbine
    app: wind-turbine
spec:
  replicas: 3
  roles:
  - broker
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 2Gi
      kraftMetadata: shared
      deleteClaim: false