{{- if .Values.followChangesForBranch }}
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ include "app.fullname" . }}-run-{{ .Release.Revision }}
  labels:
    tekton.dev/pipeline: wind-turbine-pipeline
    app.kubernetes.io/component: tekton
    app.kubernetes.io/part-of: wind-turbine
spec:
  params:
    - name: IMAGE_TAG
      value: 1.0.0
    - name: IMAGE_NAME
      value: quay.io/modzelewski/quinoa-wind-turbine
    - name: GIT_REPO
      value: 'https://github.com/gmodzelewski/quinoa-wind-turbine.git'
    - name: GIT_BRANCH
      value: 'main'
  pipelineRef:
    name: wind-turbine-pipeline
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
  - name: maven-settings
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
{{- end }}
