apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    app.openshift.io/route-disabled: "false"
    app.openshift.io/vcs-uri: {{ coalesce .Values.applicationGitUrl "https://github.com/gmodzelewski/quinoa-wind-turbine.git" }}
    secret.reloader.stakater.com/reload: "infinispan-generated-secret,quinoa-wind-turbine"
  labels:
    app: quinoa-wind-turbine
    app.kubernetes.io/instance: quinoa-wind-turbine
    app.kubernetes.io/name: quinoa-wind-turbine
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: wind-turbine
    app.openshift.io/runtime: quarkus
  name: quinoa-wind-turbine
spec:
  replicas: {{ coalesce .Values.replicas 5 }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: quinoa-wind-turbine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: quinoa-wind-turbine
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: quinoa-wind-turbine
          image: "{{ include "app.image" . }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: QUARKUS_PROFILE
              value: openshift-cluster
            - name: INFINISPAN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: infinispan-generated-secret
            - name: QUARKUS_SECURITY_USERS_EMBEDDED_PLAIN_TEXT
              valueFrom:
                secretKeyRef:
                  key: plain-text-password-enabled
                  name: quinoa-wind-turbine
            - name: QUARKUS_SECURITY_USERS_EMBEDDED_USERS_DEVELOPER
              valueFrom:
                secretKeyRef:
                  key: developer-user-password
                  name: quinoa-wind-turbine
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
